# Generated by Django 3.2.18 on 2023-05-02 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('preparation_time', models.PositiveIntegerField()),
                ('category', models.CharField(default='Unknown', max_length=200)),
                ('cook_time', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(default='default_image.png', upload_to='images/')),
                ('spiciness', models.IntegerField(choices=[(1, 'Mild'), (2, 'Medium'), (3, 'Hot'), (4, 'Very Hot'), (5, 'Extremely Hot')], default=1)),
                ('steps', models.TextField(default='')),
                ('categories', models.ManyToManyField(to='cookbook_app.Category')),
                ('ingredients', models.ManyToManyField(to='cookbook_app.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook_app.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook_app.recipe')),
            ],
        ),
    ]
