# Generated by Django 3.2.18 on 2023-05-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementunit',
            name='conversion_rate',
        ),
    ]
