# Generated by Django 3.2.18 on 2023-05-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0002_auto_20230520_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to=''),
        ),
    ]
