# Generated by Django 3.2.18 on 2023-05-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0002_remove_measurementunit_conversion_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='portion_size',
            field=models.IntegerField(default=1),
        ),
    ]
