# Generated by Django 3.2.18 on 2023-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0003_alter_recipe_portion_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='base_portion_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
